name: conditional job
on:
  pull_request:

jobs:
  conditional_job_check_files:
    runs-on: 'ubuntu-latest'
    # Declare outputs for next jobs
    outputs:
      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
    steps:
      - uses: actions/checkout@v2
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2
      - shell: pwsh
        id: check_file_changed
        run: |
          $branch = git branch --show-current >> $GITHUB_ENV \
          echo "$branch"
          # $diff = git diff main...$branch | grep -v '.github/*' >> $GITHUB_ENV \
          # $hasChanges = $diff.Length -gt 0 >> $GITHUB_ENV
          # Set the output named "docs_changed"
          # echo "::set-output name=changes::$hasChanges"
  # Run the job only with "docs_changed" equals "True"
  conditional_job:
    runs-on: 'ubuntu-20.04'
    needs: [conditional_job_check_files]
    if: needs.conditional_job_check_files.outputs.docs_changed == 'false'
    steps:
      - shell: pwsh
        run: echo "Ran Conditional Job"
